-- Track which language version of an article was generated by the AI
-- translator. Editors can flip the flag off after manual review.
-- translatedAt* records when the AI fill happened (for audit + UI badge).
ALTER TABLE "Article"
  ADD COLUMN "autoTranslatedFr" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN "autoTranslatedEn" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN "translatedAtFr"   TIMESTAMP(3),
  ADD COLUMN "translatedAtEn"   TIMESTAMP(3);
